/* eslint:disable */
/**
 * This file was automatically generated by json-schema-to-interface.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-interface to regenerate this file.
 */

export interface UserWatchLaterAllRemovePostResponse {
<<<<<<< HEAD
  path: SetStateAction<string>;
  success: boolean;
=======
  path: string;
>>>>>>> 2f42d32e2b68bcc887d044fcb2a892f7bc84add3
}
