/* eslint:disable */
/**
 * This file was automatically generated by json-schema-to-interface.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-interface to regenerate this file.
 */

export interface UserWatchLaterAddPostResponse {
  success: boolean;
}
